<?php
namespace Database\Seeders;
use App\Models\{FraudFlag,Listing,User}; use Illuminate\Database\Seeder; use Illuminate\Support\Facades\Hash;
class DatabaseSeeder extends Seeder {public function run():void{
 $admin=User::create(['name'=>'DelsuMart Administrator','matric_no'=>'ADMIN001','email'=>'admin@delsumart.test','programme'=>'Administration','level'=>'Staff','password'=>Hash::make('DemoAdmin2026!'),'role'=>'admin']);
 $verified=User::create(['name'=>'Ada Okafor','matric_no'=>'DEMO/CSC/001','email'=>'ada@delsumart.test','programme'=>'Computer Science','level'=>'400','password'=>Hash::make('DemoStudent2026!')]);$verified->verification()->create(['matric_no'=>$verified->matric_no,'full_name'=>$verified->name,'programme'=>$verified->programme,'level'=>$verified->level,'id_card_image'=>'demo/private-id','fee_receipt_image'=>'demo/private-fee','verification_status'=>'verified','verified_by'=>$admin->id,'verified_at'=>now()]);
 $pending=User::create(['name'=>'Tega Efe','matric_no'=>'DEMO/ACC/002','email'=>'tega@delsumart.test','programme'=>'Accounting','level'=>'300','password'=>Hash::make('DemoStudent2026!')]);$pending->verification()->create(['matric_no'=>$pending->matric_no,'full_name'=>$pending->name,'programme'=>$pending->programme,'level'=>$pending->level,'id_card_image'=>'demo/private-id','fee_receipt_image'=>'demo/private-fee','verification_status'=>'pending']);
 $rejected=User::create(['name'=>'Ese James','matric_no'=>'DEMO/ECO/003','email'=>'ese@delsumart.test','programme'=>'Economics','level'=>'200','password'=>Hash::make('DemoStudent2026!')]);$rejected->verification()->create(['matric_no'=>$rejected->matric_no,'full_name'=>$rejected->name,'programme'=>$rejected->programme,'level'=>$rejected->level,'id_card_image'=>'demo/private-id','fee_receipt_image'=>'demo/private-fee','verification_status'=>'rejected','verified_by'=>$admin->id,'verified_at'=>now(),'rejection_reason'=>'Fee receipt is not readable. Please upload a clear current-session copy.']);
 foreach([['HP EliteBook 840 G7','Laptops & Computers',385000],['Calculus Textbook Bundle','Books & Academic Materials',12000],['UI Design Tutoring','Services',8000]] as $x)Listing::create(['user_id'=>$verified->id,'title'=>$x[0],'description'=>'Demo listing created for project evaluation and interface testing.','category'=>$x[1],'price'=>$x[2],'status'=>'active']);
 FraudFlag::create(['related_type'=>'account','related_id'=>$rejected->id,'flag_reason'=>'Three or more KYC resubmissions (+20); repeated rejected verification attempts (+20)','risk_score'=>40,'status'=>'open']);
 }}
