@extends('layouts.admin')
@section('title','Review student verification')
@section('content')
<a href="{{ route('admin.verifications') }}" class="text-sm font-bold text-blue-600">← KYC reviews</a>
<div class="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-[.2em] text-blue-600">PRIVATE STUDENT VERIFICATION</p><h1 class="mt-2 text-3xl font-black">{{ $verification->full_name }}</h1><p class="mt-2 text-slate-500">Review the student's information and both submitted documents before recording a decision.</p></div><span class="rounded-full px-3 py-1.5 text-xs font-black uppercase {{ $verification->verification_status==='verified'?'bg-emerald-100 text-emerald-800':($verification->verification_status==='rejected'?'bg-red-100 text-red-800':'bg-amber-100 text-amber-800') }}">{{ $verification->verification_status }}</span></div>
<div class="mt-8 grid gap-6 xl:grid-cols-[1fr_360px]"><div class="space-y-6">
<section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-black">Student information</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2">@foreach(['Full name'=>$verification->full_name,'Matric number'=>$verification->matric_no,'Email'=>$verification->user->email,'Programme'=>$verification->programme,'Level'=>$verification->level,'Last submitted'=>$verification->updated_at->format('d M Y, H:i'),'Resubmissions'=>$verification->resubmission_count] as $label=>$value)<div><dt class="text-xs font-bold uppercase text-slate-400">{{ $label }}</dt><dd class="mt-1 font-semibold">{{ $value }}</dd></div>@endforeach</dl></section>
<section class="rounded-2xl border bg-white p-6 shadow-sm"><div><h2 class="text-lg font-black">Submitted documents</h2><p class="mt-1 text-sm text-slate-500">These URLs are authorized controller routes. Raw private storage paths are never exposed.</p></div><div class="mt-6 grid gap-5 md:grid-cols-2">
@foreach([['id-card','Student ID card',$verification->id_card_image],['fee-receipt','Current school-fee receipt',$verification->fee_receipt_image]] as [$type,$label,$path])
<div class="overflow-hidden rounded-2xl border bg-slate-50"><div class="listing-photo aspect-[4/3] bg-slate-100">@if(preg_match('/\.(jpe?g|png)$/i',$path))<img class="h-full w-full object-contain" src="{{ route('kyc.documents.show',[$verification,$type]) }}" alt="{{ $label }}">@else<div class="grid h-full place-items-center p-6 text-center"><div><div class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-red-100 font-black text-red-700">PDF</div><p class="mt-3 text-sm font-bold">Secure PDF document</p></div></div>@endif</div><div class="flex items-center justify-between gap-3 border-t bg-white p-4"><strong class="text-sm">{{ $label }}</strong><a target="_blank" rel="noopener" class="text-sm font-bold text-blue-600" href="{{ route('kyc.documents.show',[$verification,$type]) }}">View PDF / document ↗</a></div></div>
@endforeach
</div></section>
<section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-black">Review history</h2><div class="mt-4 divide-y">@forelse($history as $log)<div class="py-4"><div class="flex justify-between gap-4"><strong class="text-sm">{{ ucfirst(str_replace('_',' ',$log->action_type)) }}</strong><time class="text-xs text-slate-400">{{ $log->created_at->format('d M Y, H:i') }}</time></div><p class="mt-2 text-sm text-slate-600">{{ $log->notes }}</p><p class="mt-1 text-xs text-slate-400">{{ $log->admin?->name ?? 'System' }}</p></div>@empty<p class="py-4 text-sm text-slate-500">No previous review decisions.</p>@endforelse</div></section>
</div><aside class="space-y-5">@if($verification->rejection_reason)<div class="rounded-2xl border border-red-200 bg-red-50 p-5"><p class="font-black text-red-900">Previous rejection reason</p><p class="mt-2 text-sm text-red-800">{{ $verification->rejection_reason }}</p></div>@endif
<section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="font-black">Record decision</h2><p class="mt-2 text-sm leading-6 text-slate-500">Confirm the identity details and readability of both documents. Decisions are audited.</p>@if($verification->verification_status==='pending')<form method="POST" action="{{ route('admin.verifications.decide',$verification) }}" class="mt-5">@csrf @method('PATCH')<input type="hidden" name="decision" value="verified"><button class="w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white">Approve verification</button></form><form method="POST" action="{{ route('admin.verifications.decide',$verification) }}" class="mt-4 space-y-3">@csrf @method('PATCH')<input type="hidden" name="decision" value="rejected"><label class="text-sm font-bold" for="reason">Rejection reason</label><textarea id="reason" name="reason" required maxlength="1000" rows="4" class="w-full rounded-xl border px-3 py-3" placeholder="Tell the student exactly what needs to be corrected."></textarea><button class="w-full rounded-xl border border-red-200 px-4 py-3 text-sm font-bold text-red-700">Reject submission</button></form>@else<p class="mt-5 rounded-xl bg-slate-50 p-4 text-sm">Reviewed by {{ $verification->reviewer?->name ?? 'Administrator' }} on {{ $verification->verified_at?->format('d M Y, H:i') }}.</p>@endif</section>
<div class="rounded-2xl bg-slate-950 p-5 text-sm leading-6 text-slate-300"><strong class="text-white">Private by design.</strong><br>Documents remain in private storage and access is authorized on every request.</div></aside></div>
@endsection