<?php
namespace App\Http\Controllers;
use App\Models\{AuditLog,Dispute,FraudFlag,Listing,Transaction,User,Verification}; use App\Notifications\KycStatusNotification; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class AdminController extends Controller {
 public function dashboard(){return view('admin.dashboard',['stats'=>['students'=>User::where('role','student')->count(),'verified'=>Verification::where('verification_status','verified')->count(),'pending'=>Verification::where('verification_status','pending')->count(),'rejected'=>Verification::where('verification_status','rejected')->count(),'listings'=>Listing::where('status','active')->count(),'held'=>Transaction::where('status','paid_held')->count(),'disputes'=>Dispute::whereIn('status',['open','under_review'])->count(),'flags'=>FraudFlag::where('status','open')->count()],'pending'=>Verification::with('user')->where('verification_status','pending')->latest()->take(8)->get()]);}
 public function verifications(){return view('admin.verifications',['verifications'=>Verification::with('user')->latest()->paginate(20)]);}
 public function decide(Request $r,Verification $verification){$d=$r->validate(['decision'=>'required|in:verified,rejected','reason'=>'nullable|required_if:decision,rejected|string|max:1000']);DB::transaction(function()use($r,$verification,$d){$verification->update(['verification_status'=>$d['decision'],'verified_by'=>$r->user()->id,'verified_at'=>now(),'rejection_reason'=>$d['decision']==='rejected'?$d['reason']:null]);AuditLog::create(['admin_id'=>$r->user()->id,'action_type'=>'kyc_'.$d['decision'],'target_type'=>'verification','target_id'=>$verification->id,'notes'=>$d['reason']??'Student identity documents reviewed.']);});$verification->user->notify(new KycStatusNotification($d['decision'],$d['reason']??null));return back()->with('success','Verification decision recorded.');}
 public function flags(){return view('admin.flags',['flags'=>FraudFlag::latest()->paginate(20)]);}
 public function reviewFlag(Request $r,FraudFlag $flag){$d=$r->validate(['status'=>'required|in:reviewed,dismissed']);$flag->update(['status'=>$d['status'],'reviewed_by'=>$r->user()->id,'reviewed_at'=>now()]);AuditLog::create(['admin_id'=>$r->user()->id,'action_type'=>'fraud_'.$d['status'],'target_type'=>'fraud_flag','target_id'=>$flag->id]);return back()->with('success','Fraud flag updated.');}
 public function audits(){return view('admin.audits',['logs'=>AuditLog::with('admin')->latest()->paginate(30)]);}
}